#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Laravel Artisan CLI
|--------------------------------------------------------------------------
|
| This script provides the entry point to send console commands
| to the Laravel application. You may modify this file if you
| wish to change the way it operates with your Laravel app.
|
*/

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/bootstrap/autoload.php';
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
